# Generated by Django 4.2.9 on 2024-01-26 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0003_alter_usermodel_qr'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='qr',
        ),
        migrations.AddField(
            model_name='usermodel',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
