# Generated by Django 3.2.12 on 2024-02-01 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0003_alter_usermodel_qr_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
