# Generated by Django 3.2.12 on 2024-02-15 13:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0004_alter_usermodel_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultymodel',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='abbreviation'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foydalanuvchilar', to='back.eventmodel', verbose_name='event'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foydalanuvchilar', to='back.facultymodel', verbose_name='faculty'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foydalanuvchilar', to='back.groupmodel', verbose_name='group'),
        ),
    ]
