# Generated by Django 3.2.12 on 2024-02-15 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0005_auto_20240215_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventmodel',
            name='event_name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='event_name'),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='event_name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='event_name'),
        ),
        migrations.AddField(
            model_name='eventmodel',
            name='event_name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='event_name'),
        ),
        migrations.AddField(
            model_name='facultymodel',
            name='abbreviation_en',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='abbreviation'),
        ),
        migrations.AddField(
            model_name='facultymodel',
            name='abbreviation_ru',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='abbreviation'),
        ),
        migrations.AddField(
            model_name='facultymodel',
            name='abbreviation_uz',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='abbreviation'),
        ),
        migrations.AddField(
            model_name='facultymodel',
            name='faculty_name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='faculty_name'),
        ),
        migrations.AddField(
            model_name='facultymodel',
            name='faculty_name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='faculty_name'),
        ),
        migrations.AddField(
            model_name='facultymodel',
            name='faculty_name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='faculty_name'),
        ),
    ]
