# Generated by Django 3.2.12 on 2024-02-15 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0006_auto_20240215_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='back.eventmodel', verbose_name='event'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='back.facultymodel', verbose_name='faculty'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='back.groupmodel', verbose_name='group'),
        ),
    ]
