# Generated by Django 3.2.12 on 2024-03-26 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0009_auto_20240224_1157'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnotherUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_degree', models.CharField(blank=True, max_length=30, null=True, verbose_name='academic_degree')),
                ('first_name', models.CharField(max_length=100, verbose_name='first_name')),
                ('last_name', models.CharField(max_length=100, verbose_name='last_name')),
                ('phone_number', models.CharField(max_length=13, verbose_name='phone_number')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created_at')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='another_users', to='back.eventmodel', verbose_name='event')),
            ],
            options={
                'verbose_name': 'another user',
                'verbose_name_plural': 'another users',
            },
        ),
    ]
