# Generated by Django 3.2.12 on 2024-03-27 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0010_anotherusermodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventmodel',
            name='event_name_en',
        ),
        migrations.RemoveField(
            model_name='eventmodel',
            name='event_name_ru',
        ),
        migrations.RemoveField(
            model_name='eventmodel',
            name='event_name_uz',
        ),
        migrations.RemoveField(
            model_name='facultymodel',
            name='abbreviation_en',
        ),
        migrations.RemoveField(
            model_name='facultymodel',
            name='abbreviation_ru',
        ),
        migrations.RemoveField(
            model_name='facultymodel',
            name='abbreviation_uz',
        ),
        migrations.RemoveField(
            model_name='facultymodel',
            name='faculty_name_en',
        ),
        migrations.RemoveField(
            model_name='facultymodel',
            name='faculty_name_ru',
        ),
        migrations.RemoveField(
            model_name='facultymodel',
            name='faculty_name_uz',
        ),
        migrations.AlterField(
            model_name='anotherusermodel',
            name='academic_degree',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='anotherusermodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='anotherusermodel',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='another_users', to='back.eventmodel'),
        ),
        migrations.AlterField(
            model_name='anotherusermodel',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='anotherusermodel',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='anotherusermodel',
            name='phone_number',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='event_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='eventmodel',
            name='time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='facultymodel',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='facultymodel',
            name='faculty_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='groupmodel',
            name='group_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='groupmodel',
            name='letter',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='back.eventmodel'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='back.facultymodel'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='back.groupmodel'),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='phone_number',
            field=models.CharField(max_length=13),
        ),
    ]
