# Generated by Django 3.2.12 on 2024-03-28 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0011_auto_20240327_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='group',
            field=models.CharField(max_length=5),
        ),
        migrations.DeleteModel(
            name='GroupModel',
        ),
    ]
